### ISSUE TITLE
Unable to install axolotl due to missing bitsandbytes==0.45.0 dependency

### ISSUE THREAD

**Issue by YijuGuo** [RLHFlow/Online-RLHF#30]
I am attempting to install axolotl using the command pip3 install --no-build-isolation -e '.[flash-attn,deepspeed]', and I encountered an issue regarding a missing dependency version.

The installation process requires bitsandbytes version 0.45.0, however, I am unable to find this specific version in the available distributions. The error message indicates that only versions up to 0.42.0 are accessible.

Is there a specific reason why the 0.45.0 version of bitsandbytes is required for axolotl installation? Could you please provide guidance or clarification on how to proceed in this situation?

Thank you for your attention to this matter. I appreciate your work on axolotl and look forward to your assistance in resolving this issue.

`pip3 install --no-build-isolation -e '.[flash-attn,deepspeed]'
Obtaining file:///home/test/OnlineDPO/axolotl
Checking if build backend supports build_editable ... done
Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of axolotl to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.45.0 (from axolotl) (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.45.0`

**Comment by WeiXiongUST** [comment]
Hi we recommend you to use 0.4.1 by following the instruction we provide. This version is rather stable with many tests.

**Comment by YijuGuo** [comment]
> Hi we recommend you to use 0.4.1 by following the instruction we provide. This version is rather stable with many tests.

I am encountering difficulties installing axolotl as per the specified requirements that mention PyTorch >=2.3.1. The installation process fails when using PyTorch 2.1.2, resulting in a numpy dependency error.

Error message:

`Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [57 lines of output]
    Traceback (most recent call last):
      File "/home/test/test05/anaconda3/envs/gyj_sft/lib/python3.10/site-packages/numpy/_core/__init__.py", line 23, in <module>
        from . import multiarray
      File "/home/test/test05/anaconda3/envs/gyj_sft/lib/python3.10/site-packages/numpy/_core/multiarray.py", line 10, in <module>
        from . import overrides
      File "/home/test/test05/anaconda3/envs/gyj_sft/lib/python3.10/site-packages/numpy/_core/overrides.py", line 7, in <module>
        from numpy._core._multiarray_umath import (
    ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/test/test05/anaconda3/envs/gyj_sft/lib/python3.10/site-packages/numpy/_core/_multiarray_umath.cpython-310-x86_64-linux-gnu.so)`

It seems that the specified torch version is conflicting with numpy dependencies. Could you please provide guidance on resolving this issue? Additionally, could you clarify the correct PyTorch version required for axolotl installation?

Thank you for your assistance in advance. I appreciate your prompt attention to this matter.
